addressbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('book/', include('book.urls')),
    path('admin/', admin.site.urls),
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    # home page
    path("", views.index, name="index"),
    # generate formular to create a new contact
    path("create/", views.create, name="create"),
    # contact details
    path("<int:contact_id>/contacts/", views.details, name="details"),
    # process the creation of a new contact
    path("add/", views.process_create, name="process_create"),
    # generate formular to update a contact
    path("<int:contact_id>/update/", views.update, name="update"),
    # process the update of a contact
    path("<int:contact_id>/process_update/", views.process_update, name="process_update"),
    # process the deletion
    path("<int:contact_id>/process_delete/", views.process_delete, name="process_delete"),
]

book/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.CharField(max_length=255)
    photo = models.ImageField()

    def __str__(self):
        return f"{self.name} {self.lastname}"

book/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Contact
from django.http import HttpResponseRedirect
# Create your views here.
def index(request):
    contacts = get_list_or_404(Contact)
    context = {'contact_list': contacts}
    return render(request, "book/index.html", context)

def details(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)
    context = {"contact":contact}
    return render(request, "book/details.html", context)

def create(request):
    return render(request, "book/create.html")

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)
    context = {"contact":contact}
    return render(request, "book/update.html", context)

def process_create(request):
    type_daction = request.POST.get("action")
    if type_daction == "add":

        new_contact = Contact()

        new_contact.name = request.POST.get("name")
        new_contact.lastname = request.POST.get("lastname")
        new_contact.phone = request.POST.get("phone")
        new_contact.email = request.POST.get("email")
        new_contact.email = request.POST.get("email")
        new_contact.address = request.POST.get("email")
        new_contact.photo = request.POST.get("photo")
        new_contact.save()

        return HttpResponseRedirect(reverse("book:index", args=()))
    

def process_update(request, contact_id):

        contact = get_object_or_404(Contact, pk=contact_id)
        contact.name = request.POST.get("name")
        contact.lastname = request.POST.get("lastname")
        contact.phone = request.POST.get("phone")
        contact.email = request.POST.get("email")
        contact.address = request.POST.get("address")
        contact.photo = request.FILES.get("photo", contact.photo)
        contact.save()
        return HttpResponseRedirect(reverse("book:index", args=()))


def process_delete(request, contact_id):
        contact = get_object_or_404(Contact, pk=contact_id)
        contact.delete()
        return HttpResponseRedirect(reverse("book:index", args=()))
    

book/templates/book/_form.html
{% load static %}

<div class="mb-3 mt-3">
    <label for="name"class="form-label">Name</label>
    <input class="form-control" type="text" name="name" id="name" value="{{name}}">
</div>
<div class="mb-3">
    <label for="lastname" class="form-label">Last name</label>
    <input class="form-control" type="text" name="lastname" id="lastname" value="{{lastname}}">
</div>
<div class="mb-3">
    <label for="phone" class="form-label">Phone</label>
    <input class="form-control" type="text" name="phone" id="phone" value="{{phone}}">
</div>
<div class="mb-3">
    <label for="email" class="form-label">e-mail</label>
    <input class="form-control" type="text" name="email" id="email" value="{{email}}">
</div>
<div class="mb-3">
    <label for="address" class="form-label">Address</label>
    <input class="form-control" type="text" name="address" id="address" value="{{adress}}">
</div>
<div class="mb-3">
    <input class="form-control" type="file" name="photo" id="photo" value="{{photo}}" accept="image/*">
</div>

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Document{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/c1f9ec2aef.js" crossorigin="anonymous"></script>
    <style>
        a {
            text-decoration: none;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-secondary bg-gradient fixed-top">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <a class="navbar-brand" href="#">LOGO</a>
                    <ul class="navbar-nav">
                        <li class="nav-item"><a aria-current="page" class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'book:index' %}"><i class="fa-regular fa-house"></i> Home</a></li>
                        <li class="nav-item"><a aria-current="page" class="nav-link {% if request.resolver_match.url_name == 'create' %}active{% endif %}" href="{% url 'book:create' %}"><i class="fa-solid fa-circle-plus"></i> Create</a></li>
                        <li class="nav-item"><a aria-current="page" class="nav-link {% if request.resolver_match.url_name == 'config' %}active{% endif %}" href="{% url 'admin:index' %}"> <i class="fa-solid fa-gear"></i>Config</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mb-5"><br></div>


    {% block content%}
    {% endblock %}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const deleteLinks = document.querySelectorAll('.delete-link');

            deleteLinks.forEach(link => {
                link.addEventListener('click', function(event) {
                    const confirmation = confirm('Êtes-vous sûr de vouloir supprimer ce contact ? Cette action est irréversible.');

                    if (!confirmation) {
                        event.preventDefault();
                    }
                });
            });
        });
    </script>
</body>

</html>

book/templates/book/create.html
{% extends "book/base.html" %}

{% block content %}
    <div class="container mt-3">
        <h3 class="text-center"  >CREATION D'UN CONTACT</h3>
        <div class="row justify-content-center">
           <div class="box-center col-md-4 col-sm-6 my-3 shadow">
               <form action="{% url 'book:process_create' %}" method="post" encrypt="multipart/form-data">
                   {% csrf_token %}
                   {% include "book/_form.html" %}
                   <button class="btn btn-secondary mb-2 " type="submit" name="action" value="add">Submit</button>
                   <button class="btn btn-warning mb-2 " type="reset" name="action" value="reset">Reset</button>
               </form>
           </div> 
        </div>
    </div>
{% endblock %}

book/templates/book/details.html
{% extends "book/base.html" %}
{% load static %}

{% block content %}
    {% if contact %}
    <h3 class="text-center mt-3 mb-3" >PLUS DE DETAILS SUR UN(E) CONTACT : </h3>
        <div class="container">
            <div class="row">
                <div class="col-md-3 mb-5 ">
                    <div class="card " style="width: 18rem;">
                        <img class="card-img-top" src="" alt="">
                        <div class="card-body">
                            <H5 class="card-title">card title </H5>
                            <p class="card-text">contenu de la carte</p>
                            <a class="btn btn-primary" href="{% url 'book:update' contact.id %}">Modifier</a>
                            <a class="btn btn-danger delete-link" href="{% url 'book:process_delete' contact.id %}">Supprimer</a>
                        </div>
                    </div>
                </div>
                <div class="col shadow mb-5" style="height:80vh;">
                    <table class="table mt-2">
                        <tr>
                            <th scope="row">Nom :</th>
                            <td>{{contact.name}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Prenom :</th>
                            <td>{{contact.lastname}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Téléphone :</th>
                            <td>{{contact.phone}}</td>
                        </tr>
                        <tr>
                            <th scope="row">e-mail :</th>
                            <td>{{contact.email}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Addresse :</th>
                            <td>{{contact.address}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    {% else %}
        Aucun contact à affichier pour l'instant
    {% endif %}
{% endblock %}

book/templates/book/index.html
{% extends 'book/base.html' %}
{% load static %}
{%block content%}
<div class="row justify-content-center mt-5 mb-5">
    <div class="col-md-6 border rounded shadow bg-secondary text-dark bg-gradient bg-opacity-10">
        <h3 class="text-center mt-3 " style="text-shadow: 2px 2px 3px blueviolet;">LISTE DES CONTACTES</h3>
        <hr>
        {% if contact_list %}
            <ul>
                {% for contact in contact_list%}
                    <li class="card mb-2">
                        <div class="row g-0">
                            <div class="col-md-2">
                                <img src="" class="img-fluid rounded-start" alt="pdp">
                            </div>
                            <div class="col-md-8" style="width:68%;">
                                <div class="card-body ">
                                    <a class ="card-title " href="{% url 'book:details' contact.id %}" >{{contact.name}} {{ contact.lastname}}</a>
                                    <p>{{ contact.phone }}</p>
                                </div>
                            </div>
                            <div class="col-md-8 mt-3" style=" width:fit-content; height:fit-content;">                                
                                <a class="btn btn-secondary"href="{% url 'book:update' contact.id %}"> <i class="fa-solid fa-pen-to-square"></i></a><!-- Modifier -->
                                <a class="btn btn-danger delete-link"href="{% url 'book:process_delete' contact.id %} "><i class="fa-solid fa-trash"></i></a><!-- Supprimer -->
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Aucun contact pour l'instant</p>
        {% endif %}
    </div>
</div>

{% endblock %}

book/templates/book/update.html
{% extends "book/base.html"%}
{% load static %}

{% block content %}
    {% if not contact %}
        <div class="container">
            <p>Aucun contact séléctionnée pour une mis à jour ou suppression éventuelle </p>
        </div>
    {% else %}
        {# eto izy raha manao update #}
        <div class="container mt-3 ">
            <h3 class="text-center " >MIS A JOUR DU CONTACT</h3>
            <div class="row justify-content-center">
                <div class="box-center col-md-4 col-sm-6 my-3 shadow">
                    <form action="{% url 'book:process_update' contact.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "book/_form.html" with entete='Mis à jour du Contact' name=contact.name lastname=contact.lastname phone=contact.phone email=contact.email adress=contact.address photo=contact.photo%}
                        <button class="btn btn-secondary mb-2 " type="submit" name="action" value="update">Submit</button>
                        <button class="btn btn-warning mb-2 " type="reset" name="action" value="reset">Reset</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}